DELETE http://localhost:3000/myblog/comments/65de4d21c3291319be32ad12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Yzc2ZGQwZTU0N2Q5YTU3ODczZjAyZiIsImVtYWlsIjoiY2FtaWxhQGdtYWlsLmNvbSIsImlhdCI6MTcwNzU3NTA4M30.jVAUMCE7uHsksGnStv9p0ts6oKj3QlkYFJLsCuvxmQs