DELETE http://localhost:3000/myblog/users/65de54aa63a6c9381c305406
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGU1NGFhNjNhNmM5MzgxYzMwNTQwNiIsImVtYWlsIjoiY2FtaWxhQGdtYWlsLmNvbSIsImlhdCI6MTcwOTA2OTU5OH0.NtIq5rZ7oUhhobvHWtbv8ZfbOAFhokv6BkmgIMv9Qls