POST http://localhost:3000/myblog/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGU1NTkxNjNhNmM5MzgxYzMwNTRhYSIsImVtYWlsIjoiY2FtaWxhQG1haWwuY29tIiwiaWF0IjoxNzA5MTIxNzAzfQ.bUdZ_QVkpu7R7I38_v5dNylS9SP9wxMmIwUFg9nIDms

{
    "name": "Backend"
}