DELETE http://localhost:3000/myblog/categories/65de4e7ec3291319be32ad2b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZDRhZTNmZjBkMWY3YjhiNTJkODViZiIsImVtYWlsIjoiY2FtaWxAZ21haWwuY29tIiwiaWF0IjoxNzA5MDQ4MzQxfQ.SSFR_VAF2v7GozfgEsomTDr0pHwuhKotfWd_9qw2R_8